// Autogenerated C header file for LCD
#ifndef _JACDAC_SPEC_LCD_H
#define _JACDAC_SPEC_LCD_H 1

#define JD_SERVICE_CLASS_LCD  0x1b7567b4

/**
 * Read-write ratio u0.8 (uint8_t). Sets the brightness of the display.
 */
#define JD_LCD_REG_BRIGHTNESS JD_REG_INTENSITY

/**
 * Read-only # uint16_t. Width of the display, in pixels.
 */
#define JD_LCD_REG_WIDTH 0x180

/**
 * Read-only # uint16_t. Height of the display, in pixels.
 */
#define JD_LCD_REG_HEIGHT 0x181

/**
 * Argument: command bytes. Runs the specified command.
 */
#define JD_LCD_CMD_RUN 0x81

#endif
